
name: Build and test

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  macos:
    strategy:
      matrix:
        os: [ macOS-13, macOS-14 ]
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v1

    - name: "Build app for iPhone 15"
      run: xcodebuild -scheme SimpleApp -configuration Debug -target SimpleApp -destination 'name=iPhone 15,platform=iOS Simulator,arch=x86_64' -derivedDataPath ./build

    - name: Boot iPhone 15 simulator.
      run: |
        xcrun simctl list devices
        xcrun simctl boot 'iPhone 15'

    - name: install app on simulator
      run: |
        xcrun simctl install booted build/Build/Products/Debug-iphonesimulator/SimpleApp.app/
        xcrun simctl listapps booted

    - name: Launch app on simulator
      run: |
        xcrun simctl launch booted com.simlay.net.SimpleApp

    - name: Get screenshot of app
      run: |
        xcrun simctl io booted screenshot screen.png

    - uses: actions/upload-artifact@v4
      with:
        name: screen.png
        path: screen.png
